version: "3.9"

services:
  api:
    container_name: spotsat
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ".env"
    ports:
      - "80:80"
    volumes:
      - ./log:/code/log
